import db from "@/lib/db";
import invoice from "@/modal/invoice";
import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req) {
    await db();
    const formdata = await req.formData();
    const id = formdata.get("id");
    const companyName = formdata.get("companyName");
    const companyEmail = formdata.get("companyEmail");
    const companyWebsite = formdata.get("companyWebsite");
    const clientName = formdata.get("clientName");
    const clientEmail = formdata.get("clientEmail");
    const clientAddress = formdata.get("clientAddress");
    const clientContact = formdata.get("clientContact");
    const invoiceData = JSON.parse(formdata.get("invoice"));
    const isExist = await invoice.countDocuments({ id });
    if (!isExist) await invoice.create({ id, companyName, companyEmail, companyWebsite, clientName, clientEmail, clientAddress, clientContact, invoice: invoiceData });
    const invoiceId = `${req.headers.get("origin")}/${id}`;
    const transporter = nodemailer.createTransport({
        host: "smtp.hostinger.com",
        port: 465,
        secure: true,
        auth: {
            user: process.env.MAIL_USER,
            pass: process.env.MAIL_PASS,
        },
    });
    await transporter.sendMail({
        from: `"${companyName}" <zero-invoice@vebedge.com>`,
        to: clientEmail,
        subject: `Your Invoice ID ${id} • ${new Date().toLocaleDateString()}`,
        html: `
<div style="font-family: Arial, Helvetica, sans-serif; background-color: #ffffff; padding: 30px; color: #000;">
  <p style="margin-bottom: 30px;">
    <a href="${invoiceId}" style="display: inline-block; padding: 12px 44px; background: #000; color: #fff; text-decoration: none; font-size: 15px; font-weight: bold;">
      View Invoice
    </a>
  </p>
  <p style="font-size: 13px; color: #555; margin-bottom: 20px;">
    Digital invoice generated by <strong>Zero Invoice</strong><br>
    Developed by <strong>Veb Edge</strong>.
  </p>
  <p style="font-size: 12px; color: #888;">
    © ${new Date().getFullYear()} Veb Edge. All rights reserved.
  </p>
</div>
        `
    });
    return NextResponse.json(200);
}